//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Note.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My_Note.Lang.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Picture 的本地化字符串。
        /// </summary>
        public static string AddPageAppbarButtonCamera {
            get {
                return ResourceManager.GetString("AddPageAppbarButtonCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string AddPageAppbarButtonSave {
            get {
                return ResourceManager.GetString("AddPageAppbarButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plese Input Main Body in Here 的本地化字符串。
        /// </summary>
        public static string AddPageHintText {
            get {
                return ResourceManager.GetString("AddPageHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Title in Here 的本地化字符串。
        /// </summary>
        public static string AddPageHintTitle {
            get {
                return ResourceManager.GetString("AddPageHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Note 的本地化字符串。
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, Dividend can not be 0 的本地化字符串。
        /// </summary>
        public static string CalculateDivErro {
            get {
                return ResourceManager.GetString("CalculateDivErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All Data and Initialize Software 的本地化字符串。
        /// </summary>
        public static string ClearButtonSubTitle {
            get {
                return ResourceManager.GetString("ClearButtonSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Cache 的本地化字符串。
        /// </summary>
        public static string ClearButtonTitle {
            get {
                return ResourceManager.GetString("ClearButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to Exit? 的本地化字符串。
        /// </summary>
        public static string ExitMessageText {
            get {
                return ResourceManager.GetString("ExitMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Font Size and Script 的本地化字符串。
        /// </summary>
        public static string FontChangeSubTitle {
            get {
                return ResourceManager.GetString("FontChangeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Setting 的本地化字符串。
        /// </summary>
        public static string FontChangeTitle {
            get {
                return ResourceManager.GetString("FontChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAQ:
        ///1 Why homepage Loading seems a bit slow?
        ///Answer: Because the home page load a little bit complicated, so the load time is first loaded into the interface and then load the content, and therefore cause looks like a little &quot;card&quot;
        ///
        ///2 style of recording only a bunch of digital as the file name, good ugly ah can improve it?
        ///Answer: further Styles improvements in the tangled, temporarily recording date as the file name
        ///
        ///There are more questions, please contact myluobin@gmail.com 的本地化字符串。
        /// </summary>
        public static string HelpButtonText {
            get {
                return ResourceManager.GetString("HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string MainPageAppbarButtonAdd {
            get {
                return ResourceManager.GetString("MainPageAppbarButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting and About 的本地化字符串。
        /// </summary>
        public static string MainPageAppbarMenuSetting {
            get {
                return ResourceManager.GetString("MainPageAppbarMenuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Note 的本地化字符串。
        /// </summary>
        public static string MainPagePanoramaTitle {
            get {
                return ResourceManager.GetString("MainPagePanoramaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToolBox 的本地化字符串。
        /// </summary>
        public static string MainPageTitle2 {
            get {
                return ResourceManager.GetString("MainPageTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        public static string RecordPageTitle {
            get {
                return ResourceManager.GetString("RecordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string SettingAboutPageTitle {
            get {
                return ResourceManager.GetString("SettingAboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Help How To Use It 的本地化字符串。
        /// </summary>
        public static string SettingHelpPageSubTitle {
            get {
                return ResourceManager.GetString("SettingHelpPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string SettingHelpPageTitle {
            get {
                return ResourceManager.GetString("SettingHelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All Data 的本地化字符串。
        /// </summary>
        public static string SettingPageClearAllButtonTitle {
            get {
                return ResourceManager.GetString("SettingPageClearAllButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operate will clear all Note and Picture, Are you sure? 的本地化字符串。
        /// </summary>
        public static string SettingPageClearAllNoteMessage {
            get {
                return ResourceManager.GetString("SettingPageClearAllNoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operate will clear all Recorded Voice, Are you sure? 的本地化字符串。
        /// </summary>
        public static string SettingPageClearAllVoiceMessage {
            get {
                return ResourceManager.GetString("SettingPageClearAllVoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operate will clear all data, Are you sure? 的本地化字符串。
        /// </summary>
        public static string SettingPageClearButtonMessage {
            get {
                return ResourceManager.GetString("SettingPageClearButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string SettingPageClearButtonMessageTitle {
            get {
                return ResourceManager.GetString("SettingPageClearButtonMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Cache 的本地化字符串。
        /// </summary>
        public static string SettingPageClearButtonText {
            get {
                return ResourceManager.GetString("SettingPageClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Note 的本地化字符串。
        /// </summary>
        public static string SettingPageClearNoteButtonTitle {
            get {
                return ResourceManager.GetString("SettingPageClearNoteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Record 的本地化字符串。
        /// </summary>
        public static string SettingPageClearRecordButtonTitle {
            get {
                return ResourceManager.GetString("SettingPageClearRecordButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontFamily Change 的本地化字符串。
        /// </summary>
        public static string SettingPageFontFamily {
            get {
                return ResourceManager.GetString("SettingPageFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontSize Change 的本地化字符串。
        /// </summary>
        public static string SettingPageFontSize {
            get {
                return ResourceManager.GetString("SettingPageFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string SettingPageFontTitle {
            get {
                return ResourceManager.GetString("SettingPageFontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        public static string SettingPageThemeSelect1 {
            get {
                return ResourceManager.GetString("SettingPageThemeSelect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black 的本地化字符串。
        /// </summary>
        public static string SettingPageThemeSelect2 {
            get {
                return ResourceManager.GetString("SettingPageThemeSelect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string SettingPageThemeTitle {
            get {
                return ResourceManager.GetString("SettingPageThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string SettingPageTitle {
            get {
                return ResourceManager.GetString("SettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Theme to System or Software Self 的本地化字符串。
        /// </summary>
        public static string ThemeChangeSubTitle {
            get {
                return ResourceManager.GetString("ThemeChangeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Setting 的本地化字符串。
        /// </summary>
        public static string ThemeChangeTitle {
            get {
                return ResourceManager.GetString("ThemeChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string ViewEditPageAppbarButtonDelete {
            get {
                return ResourceManager.GetString("ViewEditPageAppbarButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string ViewEditPageAppbarButtonEdit {
            get {
                return ResourceManager.GetString("ViewEditPageAppbarButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ViewEditPageAppbarButtonSave {
            get {
                return ResourceManager.GetString("ViewEditPageAppbarButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit and View 的本地化字符串。
        /// </summary>
        public static string ViewEditTitle {
            get {
                return ResourceManager.GetString("ViewEditTitle", resourceCulture);
            }
        }
    }
}
